name: bachelor_heaven
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  lottie: ^2.2.0
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.3
  intl: ^0.18.0
  anim_search_bar: ^2.0.3
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.6+2
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.2
  firebase_storage: ^11.0.14
  firebase_core: ^2.7.0
  fluttertoast: ^8.2.1
  google_sign_in: ^6.0.1
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/
    - assets/category/

  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: assets\fonts\Ubuntu-Regular.ttf\
  #   - family: OoohBaby
  #     fonts:
  #       - asset: assets\fonts\OoohBaby-Regular.ttf\
